# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee0385ce5dbbc1be4513efe95c6cb891cc5d27dba53276cb22792aa7256c88094846559743e660aba24169629481af61d943084b79f3d5d0799d31ee30062280

test:
  secret_key_base: 5e1ded895be03575a76e67517fb3dcad981ed2e74ac972501cdbf46c1637edaea9433e3c717ff78f99141c073566333f2e78354a3ce8b138b8b68131063f40d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
